### ISSUE TITLE
I may take over this project

### ISSUE THREAD

**Issue by moebiuseye** [outini/pymailq#11]
Hello! 

I've thought about this cool project of yours and I'm considering taking over development. 

You can take a look at [the dev branch of my fork](https://github.com/moebiuseye/pymailq/tree/dev) and share your thoughts. 

I've integrated [a bit of unit testing with travis](https://travis-ci.org/moebiuseye/pymailq), implemented date-range selections (it works with multiple date ranges like this:) `2016-01-01 -1990-09-09 2016-08-29..2016-09-05 +2016-12-25`  

My next objective is to have a lot more of unit tests, and I will only add new features when I'm done unit testing the whole project; I needed that date-picking feature right away, though. ;)

**Comment by moebiuseye** [comment]
One of the next features that I want to implement is a delay between actions and a limit in the number of processed mail, like this:
~~~
PyMailq (sel:85478)> select sender goodguy@domain.lol
PyMailq (sel:4594)> super requeue limit 30
Requeued 30 mails
~~~

~~~
PyMailq (sel:4574)> select sender goodguy@domain.lol
PyMailq (sel:2944)> super requeue delay 0.5s
Requeued 2944 mails
~~~

**Comment by outini** [comment]
Hi,

Sorry, I missed your issue (I was not really active on my github account).
I've been inactive for a long time, but I'm making this project alive again.

I'll be glad to accept your merge requests to respond to your needs, or even implement missing functionnalities you may need. However I cannot just leave this project, sorry :/

**Comment by outini** [comment]
By the way, I looked at your date selection function and I like it a lot !
Would you make a PR ?

The Travis integration is great too, I'm actually implementing pytest and code coverage to complete it.

**Comment by moebiuseye** [comment]
I'll make a PR today if I find the time. Thanks. :)

**Comment by outini** [comment]
Thank you :)
