### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by JocelynDelalande** [outini/pymailq#8]
… and enter the hall of fame of python modules  ;)

**Comment by moebiuseye** [comment]
This should really be done. 
I really like what you've done. I was looking for libraries to do something similar. 
I owe YOU a beer! :)

**Comment by outini** [comment]
Hi,

I've been inactive for a while on this project (sorry for that).
I just published a beta version 0.5.4 in which the setup.py has been fixed.

https://pypi.python.org/pypi/pymailq

I'm making this project alive again.

Regards,
